#!/bin/sh
runlevel=S
export unlevel

/bin/hostname mcuzone
[ -d "/proc/1" ] || mount /proc

/bin/mount -av

echo "starting mdev."
/bin/mount -t sysfs sysfs /sys
/bin/echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
ifconfig eth0 192.168.1.200
route add default gw 192.168.1.1
/etc/init.d/rc.local